### ISSUE TITLE
Does not work?

### ISSUE THREAD

**Issue by danilopaulinodasilva** [vitaly-t/gulp-decomment#4]
Hi!

I'm struggling to get it working since yesterday. I have a simple .css file with some comment lines into.
But when I try to run the Gulp task always I receive this error:

[17:52:08] Using gulpfile /usr/local/var/www/teste-css/gulpfile.js
[17:52:08] Starting 'default'...

/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:5008
	            throw error;
	            ^
Error: Line 3: Unexpected token ILLEGAL
    at ErrorHandler.constructError (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:5028:27)
    at ErrorHandler.throwError (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:5164:35)
    at Scanner.scanPunctuator (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:5667:19)
    at Scanner.lex (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:6264:22)
    at Tokenizer.getNextToken (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:6675:84)
    at Object.tokenize (/usr/local/var/www/teste-css/node_modules/esprima/dist/esprima.js:154:36)
    at Object.parseRegEx (/usr/local/var/www/teste-css/node_modules/decomment/lib/utils.js:37:13)
    at parser (/usr/local/var/www/teste-css/node_modules/decomment/lib/parser.js:35:27)

This is a fresh project, just for testing. I'm using Gulp 3.9.1 and Node 7.6.0

Thanks,

**Comment by vitaly-t** [comment]
Apologies for the late response. GitHub notifications are to blame for not working right.

Are you using `decomment.text` method? Because in case of CSS that's what you need. From the error, it looks like you tried to use the default method instead, and so it decides that it is looking at some invalid JavaScript.

**Comment by Sokwva** [comment]
E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5008
                    throw error;
                    ^
Error: Line 2: Unexpected token ILLEGAL
    at ErrorHandler.constructError (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5028:27)
    at ErrorHandler.throwError (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5164:35)
    at Scanner.scanPunctuator (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5667:19)
    at Scanner.lex (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:6264:22)
    at Tokenizer.getNextToken (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:6675:84)
    at Object.tokenize (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:154:36)
    at Object.parseRegEx (E:\WorkGroup\Local\Nodejs\ztest\node_modules\decomment\lib\utils.js:37:13)
    at parser (E:\WorkGroup\Local\Nodejs\ztest\node_modules\decomment\lib\parser.js:36:27) {
  index: 32,
  lineNumber: 2,
  description: 'Unexpected token ILLEGAL'
}

similar issue here.

**Comment by Sokwva** [comment]
> E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5008 throw error; ^ Error: Line 2: Unexpected token ILLEGAL at ErrorHandler.constructError (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5012:22) at ErrorHandler.createError (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5028:27) at ErrorHandler.throwError (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5035:21) at Scanner.throwUnexpectedToken (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5164:35) at Scanner.scanPunctuator (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:5667:19) at Scanner.lex (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:6264:22) at Tokenizer.getNextToken (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:6675:84) at Object.tokenize (E:\WorkGroup\Local\Nodejs\ztest\node_modules\esprima\dist\esprima.js:154:36) at Object.parseRegEx (E:\WorkGroup\Local\Nodejs\ztest\node_modules\decomment\lib\utils.js:37:13) at parser (E:\WorkGroup\Local\Nodejs\ztest\node_modules\decomment\lib\parser.js:36:27) { index: 32, lineNumber: 2, description: 'Unexpected token ILLEGAL' }
> 
> similar issue here.

private names("#") cause this issue. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields
